name: Deploy WordPress

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: 'mbstring, mysqli'

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

      - name: Install Dependencies
        run: composer install

      - name: Build Project
        run: |
          # Add build commands here if needed

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.4.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Stop Nginx and MySQL if running
            sudo service nginx stop
            sudo service mysql stop

            # Transfer files to the server
            scp -r ./* ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_REMOTE_PATH }}

            # Restart Nginx and MySQL
            sudo service nginx start
            sudo service mysql start
